version: '3'


services:

  frontend:
    build: ./frontend
    ports:
      - '8080:8080'
    restart: always


  backend:
    build: ./backend
    ports:
      - '8085:8085'
    restart: always
    depends_on:
      - mysql


  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: bestuser
      MYSQL_DATABASE: aspect_db
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - '8888:8080'
