version: '3'


services:

  frontend:
    build: ./frontend
    ports:
      - '8080:8080'
    restart: always


  backend:
    build: ./backend
    ports:
      - '5000:5000'
    restart: always
    depends_on:
      - mysql


  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: bestuser
      MYSQL_DATABASE: notebook
    restart: always


  adminer:
    image: adminer
    ports:
      - '3000:8080'
    restart: always